### ISSUE TITLE
Requires authorization every time

### ISSUE THREAD

**Issue by ursetto** [kissge/k1pwit#1]
On every press of the shortcut key, I get a dialog box asking me `1Password is trying to authorize CLI access to your account ... in iTerm2`. After clicking `Allow Access` the password is obtained. However on the next try, it pops up the dialog box again.

I noticed you did not get any dialog box in your demonstration.

Does this still work with the latest build? I have CLI `op 2.12.0` and 1Password for Mac 8.9.11 (80911019).

Thank you!

**Comment by kissge** [comment]
Thanks for your report.
Yes, I'm using k1pwit with op 2.12.0 and 1Password for Mac 8.9.11 with no problem.

The dialog box is 1Password for Mac's security functionality.

![image](https://user-images.githubusercontent.com/4177010/211183729-1c34fdb2-e7c6-4f8a-acaa-7097b6bd4963.png)

According to the document[^1], the session expires "After 10 minutes of inactivity" or "After 12 hours" (among others), and my demo video was captured while the session was active. Can you check if the dialog box shows again **right after** the first approval?

[^1]: https://developer.1password.com/docs/cli/shell-plugins/security

**Comment by ursetto** [comment]
Yes, the dialog box shows up immediately, for example if I press the key to 'run coprocess' and paste a password twice within 30 seconds, it will show up both times.

I found by adding `tty` to one of the scripts (as a debugging aid), that the pop-up terminal window (using op + fzf) uses a different tty every time. This tty might be named the same each time, but if you run `lsof` on that device name, it is clear `op`'s tty closes between uses (as you would expect).

However, using a different tty (even with the same name) will require signing in again according to a more detailed document on the CLI, because that is part of the new-style authorization model:

---

[Session credentials](https://developer.1password.com/docs/cli/biometric-security/#session-credentials)

Session credentials are used to identify the terminal window or application where 1Password CLI is invoked. The goal is to restrict the granted authorization to a single terminal. If a user authorizes account X in one terminal window, using account y in another terminal window requires another approval from the user. These credentials don't consist of any sensitive or secret information.

**The session credential for macOS is an ID that's based on the current tty, plus the start time. This way every session credential is unique, even after an ID gets reused.**

---

However, I also found you are using `op signin` in your script, which might imply you are using session tokens (OP_SESSION_FILE) instead of the CLI integration ("Connect with 1Password CLI"). According to `op signin --help`:

---

USE SESSION TOKENS

**If the integration with the 1Password app is disabled, 1Password CLI uses
a session token to authenticate commands with 1Password.com. Sessions expire
after 30 minutes of inactivity. If you sign in using 'eval $(op signin)', the
session token will automatically be stored in the environment.**

---

So, I'm thinking you might be using session tokens, which can be shared through the filesystem, whereas I have the new-style tty-based authentication active. I could be wrong, but that would explain how this works for you. I am on an older machine that doesn't support Secure Enclave, and an older OS (10.15), but I'm not sure this matters.

In that case there's nothing to be done, and I'll close this request shortly. Thanks for looking into it.

**Comment by kissge** [comment]
Thanks, that's a great investigation!

> So, I'm thinking you might be using session tokens, which can be shared through the filesystem, whereas I have the new-style tty-based authentication active.

Yeah, that explains the situation, apparently.
So let me check if I understood correctly; the 1Password authentication k1pwit using is (or would be, in near future) obsolete, and users already using new-style are unlikely to switch "back" to it?
In that case I think I need re-implement k1pwit to support the new mode.

**Comment by ursetto** [comment]
I'm not sure if the old-style authentication is deprecated; it seems like it's still supported. The documentation points to the new-style auth by default, but also refers to the old-style depending on how you search. So, it's a bit confusing.

It may not be worth it or even possible to support the newer-style auth, since coprocesses will always start with a new TTY. You might be able to hack it to have a long-running window that stays open and authorized with a single tty, but at that point, it seems you might as well just use old-style auth.

Maybe instead just a note in the README that there are two ways to authenticate, and you expect the user is using `op signin` and `op account add` instead of the `Connect with 1Password CLI` option. New users might just not realize this is possible.

Thanks again!
